export const Images = {
  //product
  woodenBowls_1: require("./product/wooden-bowls/ClassicCamwoodBowl-Small_360x.webp"),
  woodenBowls_2: require("./product/wooden-bowls/ClassicTeakWoodBowl-Regular-2_360x.webp"),
  woodenBowls_3: require("./product/wooden-bowls/CurvedDoussieWoodBowl-Regular_360x.webp"),
  woodenBowls_4: require("./product/wooden-bowls/DurianTeakWoodBowl-2_360x.webp"),
  woodenBowls_5: require("./product/wooden-bowls/GildedTeakWoodSaladBowl1_360x.webp"),
  woodenBowls_6: require("./product/wooden-bowls/StarTeakWoodBowl_360x.webp"),
  coconutBowls_1: require("./product/coconut-bowls/IMG_0945_ThomasOBrien_websize_144dpi_360x.webp"),
  coconutBowls_2: require("./product/coconut-bowls/IMG_0946_ThomasOBrien_websize_144dpi_360x.webp"),
  plates_1: require("./product/plates/PizzaPaddleTeakWoodPlate-Jumbo_360x.webp"),
  plates_2: require("./product/plates/PizzaTeakWoodTray-11.8Inch-pack_360x.webp"),
  plates_3: require("./product/plates/RectangularTeakWoodPlate-Small1_360x.webp"),
  home_1: require("./product/home/HourglassTeakWoodCandleHolderSet_360x.webp"),
  drinkware_1: require("./product/drinkware/RoundedTeakWoodTeaCup-Tall_360x.webp"),
  garden_1: require("./product/garden/hangingfiberplanter_360x.webp"),
  garden_2: require("./product/garden/hangingplanter3-pack_360x.webp"),
  garden_3: require("./product/garden/Planterpot1_180x.avif"),
  soap_dishes_1: require("./product/soap-dishes/ClassicTeakWoodSoapDish1_360x.webp"),
  utensils_1: require("./product/utensils/CoconutwoodFork_360x.webp"),
  //tab_reson
  tab_acacia: require("./wood_type/tab/tab-acacia.webp"),
  tab_bamboo: require("./wood_type/tab/tab-bamboo.avif"),
  tab_coconut_wood: require("./wood_type/tab/tab-coconut-wood.webp"),
  tab_coconut: require("./wood_type/tab/tab-coconut.webp"),
  tab_olive: require("./wood_type/tab/tab-olive.webp"),
  tab_teak: require("./wood_type/tab/tab-teak.webp"),
  //reason
  acacia: require("./wood_type/Acacia-Wood-collections-new.webp"),
  bamboo: require("./wood_type/Bamboo-Wood-collections.webp"),
  coconut_wood: require("./wood_type/Coconut-Shell-collections.webp"),
  coconut: require("./wood_type/Coconut-Wood-collections.webp"),
  olive: require("./wood_type/Olive-Wood-collections.webp"),
  teak: require("./wood_type/Teak-Wood-collections.webp"),
};
