export const Images = {
  //common
  logo: require("./logo.svg").default,
  price_tag: require("./icon-pricing.webp"),
  //product
  woodenBowls_1: require("./product/wooden-bowls/ClassicCamwoodBowl-Small_360x.webp"),
  woodenBowls_2: require("./product/wooden-bowls/ClassicTeakWoodBowl-Regular-2_360x.webp"),
  woodenBowls_3: require("./product/wooden-bowls/CurvedDoussieWoodBowl-Regular_360x.webp"),
  woodenBowls_4: require("./product/wooden-bowls/DurianTeakWoodBowl-2_360x.webp"),
  woodenBowls_5: require("./product/wooden-bowls/GildedTeakWoodSaladBowl1_360x.webp"),
  woodenBowls_6: require("./product/wooden-bowls/StarTeakWoodBowl_360x.webp"),
  coconutBowls_1: require("./product/coconut-bowls/IMG_0945_ThomasOBrien_websize_144dpi_360x.webp"),
  coconutBowls_2: require("./product/coconut-bowls/IMG_0946_ThomasOBrien_websize_144dpi_360x.webp"),
  plates_1: require("./product/plates/PizzaPaddleTeakWoodPlate-Jumbo_360x.webp"),
  plates_2: require("./product/plates/PizzaTeakWoodTray-11.8Inch-pack_360x.webp"),
  plates_3: require("./product/plates/RectangularTeakWoodPlate-Small1_360x.webp"),
  home_1: require("./product/home/HourglassTeakWoodCandleHolderSet_360x.webp"),
  drinkware_1: require("./product/drinkware/RoundedTeakWoodTeaCup-Tall_360x.webp"),
  garden_1: require("./product/garden/hangingfiberplanter_360x.webp"),
  garden_2: require("./product/garden/hangingplanter3-pack_360x.webp"),
  garden_3: require("./product/garden/Planterpot1_180x.avif"),
  soap_dishes_1: require("./product/soap-dishes/ClassicTeakWoodSoapDish1_360x.webp"),
  utensils_1: require("./product/utensils/CoconutwoodFork_360x.webp"),
  //tab_reson_homepage
  tab_acacia: require("./wood_type/tab/tab-acacia.webp"),
  tab_bamboo: require("./wood_type/tab/tab-bamboo.avif"),
  tab_coconut_wood: require("./wood_type/tab/tab-coconut-wood.webp"),
  tab_coconut: require("./wood_type/tab/tab-coconut.webp"),
  tab_olive: require("./wood_type/tab/tab-olive.webp"),
  tab_teak: require("./wood_type/tab/tab-teak.webp"),
  //reason_hompage
  acacia: require("./wood_type/Acacia-Wood-collections-new.webp"),
  bamboo: require("./wood_type/Bamboo-Wood-collections.webp"),
  coconut_wood: require("./wood_type/Coconut-Shell-collections.webp"),
  coconut: require("./wood_type/Coconut-Wood-collections.webp"),
  olive: require("./wood_type/Olive-Wood-collections.webp"),
  teak: require("./wood_type/Teak-Wood-collections.webp"),
  //features_detail
  features_worldwide: require("./detailpage/features/icon-feature-worldwide.webp"),
  features_moneyBack: require("./detailpage/features/icon-feature-money-back.webp"),
  features_freeShipping: require("./detailpage/features/icon-feature-free-shipping.avif"),
  features_expert: require("./detailpage/features/icon-feature-expert.webp"),
  //commit_detail
  handcraf: require("./detailpage/commit/icon-handcraft_60x.webp"),
  leaf: require("./detailpage/commit/icon-leaf-round_60x.webp"),
  safe: require("./detailpage/commit/icon-safe-food_60x.avif"),
  //review
  review_1: require("./review/Gorgeous_500x.webp"),
  review_2: require("./review/I_am_IN_LOVE_with_these_bowls_500x.webp"),
  review_3: require("./review/Such_awesomeness_500x.webp"),
  review_4: require("./review/These_bowls_are_perfect_500x.webp"),
  review_5: require("./review/Wooden_Bowls_500x.webp"),
  review_6: require("./review/Exceptional_Quality_500x.webp"),
  //social
  facebook: require("./social/facebook.svg").default,
  instagram: require("./social/instagram.svg").default,
  pinterest: require("./social/pinterest.svg").default,
  youtube: require("./social/youtube.svg").default,
  //care

  //common
  water_clean: require("./care/icon-water-clean.png").default,
  wash: require("./care/icon-wash.png").default,
  sun_light: require("./care/icon-sunlight.avif"),
  store: require("./care/icon-store.avif"),
  rinse_common: require("./care/icon-rinse-common.avif"),
  over_water: require("./care/icon-overwater.png").default,
  keep_dry: require("./care/icon-keep-dry.avif"),
  hot_cup: require("./care/icon-hot-cup.png").default,
  hot_bowl: require("./care/icon-hot-bowl.webp"),
  harsh_sunlight: require("./care/icon-harsh-sunlight.png").default,
  hand: require("./care/icon-hand.webp"),
  //plates
  sun_light_plate: require("./care/icon-sunlight-plate.avif"),
  soak_plate: require("./care/icon-soak-plate.avif"),
  dry_plate: require("./care/icon-dry-plate.png").default,
  wash_plate: require("./care/icon-wash-plate.webp"),
  //utensils
  rinse_utensils: require("./care/icon-rinse-utensils.avif"),
  dry_utensils: require("./care/icon-dry-utensils.png").default,
  wash_utensils: require("./care/icon-wash-utensils.png").default,
  coat_utensils: require("./care/icon-coat-utensils.png").default,
  //soap_dishes
  wash_dish: require("./care/icon-wash-dish.png").default,
  dry_dish: require("./care/icon-dry-dish.png").default,
  rinse_dish: require("./care/icon-rinse-dish.png").default,
  coat_dish: require("./care/icon-coat-dish.png").default,
};
