export const Images = {
  woodenBowls_1: require("./product/wooden-bowls/ClassicCamwoodBowl-Small_360x.webp"),
  woodenBowls_2: require("./product/wooden-bowls/ClassicTeakWoodBowl-Regular-2_360x.webp"),
  woodenBowls_3: require("./product/wooden-bowls/CurvedDoussieWoodBowl-Regular_360x.webp"),
  woodenBowls_4: require("./product/wooden-bowls/DurianTeakWoodBowl-2_360x.webp"),
  woodenBowls_5: require("./product/wooden-bowls/GildedTeakWoodSaladBowl1_360x.webp"),
  woodenBowls_6: require("./product/wooden-bowls/StarTeakWoodBowl_360x.webp"),
  coconutBowls_1: require("./product/coconut-bowls/IMG_0945_ThomasOBrien_websize_144dpi_360x.webp"),
  coconutBowls_2: require("./product/coconut-bowls/IMG_0946_ThomasOBrien_websize_144dpi_360x.webp"),
  plates_1: require("./product/plates/PizzaPaddleTeakWoodPlate-Jumbo_360x.webp"),
  plates_2: require("./product/plates/PizzaTeakWoodTray-11.8Inch-pack_360x.webp"),
  plates_3: require("./product/plates/RectangularTeakWoodPlate-Small1_360x.webp"),
  home_1: require("./product/home/HourglassTeakWoodCandleHolderSet_360x.webp"),
  drinkware_1: require("./product/drinkware/RoundedTeakWoodTeaCup-Tall_360x.webp"),
  garden_1: require("./product/garden/hangingfiberplanter_360x.webp"),
  garden_2: require("./product/garden/hangingplanter3-pack_360x.webp"),
  garden_3: require("./product/garden/Planterpot1_180x.avif"),
  soap_dishes_1: require("./product/soap-dishes/ClassicTeakWoodSoapDish1_360x.webp"),
  utensils_1: require("./product/utensils/CoconutwoodFork_360x.webp"),
  // woodenBowls_1: require('./product/wooden-bowls/ClassicCamwoodBowl-Small_360x.webp').default,
  // woodenBowls_1: require('./product/wooden-bowls/ClassicCamwoodBowl-Small_360x.webp').default,
};
